### ISSUE TITLE
Expose important classes in root module

### ISSUE THREAD

**Issue by vladcalin** [prodicus/markovipy#10]
I was wondering if the most important classes/functions that the user will use should be exposed in the ``markovipy`` module.

The importing of the ``MarkoviPy`` class would look like

```
from markovipy import MarkoviPy
```

rather than

```
from markovipy.markovipy import MarkoviPy
```

Also, in the future, as more relevant functionality will be added, it will be more straight forward for a new user to look for them in the documentation of the ``marokovipy`` module.

Any opinions on this?

**Comment by tasdikrahman** [comment]
Hey @vladcalin 

Yup. That sounds like a good/cleaner idea to work around. Would you be able to make a PR for this?

Cheers!

**Comment by vladcalin** [comment]
I opened a pull request with the change.

**Comment by tasdikrahman** [comment]
Thanks for the contribution @vladcalin. 

If not much of a trouble, can you open a PR updating the API docs, CHANGELOG and README?

**Comment by vladcalin** [comment]
Sure, working on it!

**Comment by tasdikrahman** [comment]
Hey @vladcalin .

Just checking if you are already working on this.

**Comment by vladcalin** [comment]
I am, tomorrow I will open a PR with the changes. 

Just a quick question: In the API docs, the ``MarkoviPy`` should be documented as part of the ``markovipy.markovipy`` module and ``markovipy`` module or should it appear only in the documentation of the ``markovipy`` module? In the current format, it is automatically documented in both.

**Comment by tasdikrahman** [comment]
Hey @vladcalin 

The PR was perfect, need some small changes which are not very big.
